### PR TITLE
Stereo audio

### PR DESCRIPTION
**Pull request by Cat-Ion**

### CODE REVIEW

**Comment by tjclement** [comment]
> \*Looks at https://github.com/badgeteam/ESP32-platform-firmware/pull/141#issuecomment-569558718 commented yesterday\*
> \*Looks at this PR\*

_I'll continue with thinking about how we can crack elliptic curves in logarithmic time_ 😇

\*Wonders what PR will be here tomorrow\*

**Review by tjclement — COMMENTED** [review]
Code looks nice. Clean solution, very good. Thanks! Will test on hardware later tonight.

**Comment by Cat-Ion** [comment]
> > *Looks at [#141 (comment)](https://github.com/badgeteam/ESP32-platform-firmware/pull/141#issuecomment-569558718) commented yesterday*
> > *Looks at this PR*
> 
> _I'll continue with thinking about how we can crack elliptic curves in logarithmic time_ innocent
> 
> *Wonders what PR will be here tomorrow*

I'm about to push `feature/p=np`

**Review by tjclement — APPROVED** [review]
LGTM! Works well even on WROVER modules with limited RAM.

**Pull request merged**
