### PR TITLE
Hacktivity2019

### PR DESCRIPTION
**Pull request by l-n-x**

### CODE REVIEW

**Comment by l-n-x** [comment]
i have no idea what im doing

**Comment by renzenicolai** [comment]
Hello l-n-x! Thank you for taking the time to send in this PR. I see you closed it yourself, may I ask why?

After looking at the changes I wonder: how is the new "hacktivity2019-samd" driver different from the disobey version of that driver? Could the two be combined in some way, to avoid code duplication?

Most of the errors reported by that code quality bot are problems that already exist by the way, so we can just ignore those for now.

**Comment by l-n-x** [comment]
it's an early version and has too many bugs

**Comment by annejan** [comment]
Heya @l-n-x I added Hacktivity 2019 as a badge model in Hatchery

If you want you can user the "basket" API to filter on Hacktivity apps . . 

https://badge.team/basket/hacktivity2019/list/json           - a list of all eggs for Hacktivity2019
https://badge.team/basket/hacktivity2019/categories/json     - Hacktivity2019 specific list of categories

https://badge.team/basket/hacktivity2019/search/[words]/json - Hacktivity2019 specific search for [words]
https://badge.team/basket/hacktivity2019/category/[cat]/json - data for category [cat] on Hacktivity2019

Also there is a public "page" for the Hacktivity2019 badge at https://badge.team/badge/hacktivity2019

**Comment by renzenicolai** [comment]
Can you explain the changes needed to support your badge? What are the differences from the Disobey 2019 I2C protocol?

**Comment by renzenicolai** [comment]
@l-n-x 

Hello Roland, 

I'd love to finish your efforts by getting your badge supported in our version of the firmware. Any chance you could send me a link to your project and a list of the changes you made?

Greetings,
Renze

**Comment by renzenicolai** [comment]
@l-n-x Hi there! I'm still interested in merging your changes into the main firmware tree. It's just that I would like an explanation on where your badge is different from the Disobey 2019 badge. This PR is old and stale so I am closing it. Please contact me if you wish to continue with merging your changes.

**Pull request closed without merging**
